apiVersion: batch/v1
kind: Job
metadata:
  name: go-greeter
  namespace: knowledge-transfer
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      containers:
        - name: go
          image: localhost:5000/greeter-sender-go
      restartPolicy: Never

