apiVersion: v1
kind: Service
metadata:
  name: greeter
  namespace: knowledge-transfer
spec:
  type: NodePort
  ports:
    - targetPort: 10080
      port: 80
  selector:
    app: greeter
    type: receiver

